[package]
name = "rumprt"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
x86 = "0.19.0"
syscalls = { path = "../../../../sys/interfaces/syscalls", version = "0.1.0" }
libsyscalls = { path = "../../../../sys/lib/libsyscalls", version = "0.1.0" }
console = { path = "../../../../sys/lib/console", version = "0.1.0" }
malloc = { path = "../../../../sys/lib/malloc", version = "0.1.0" }
spin = "0.5.2"
rumpkernel = { git = "https://github.com/gz/rust-rumpkernel.git", rev = "04e6cbf" }
cstr_core = { git = "https://github.com/gz/cstr_core.git", default-features = false, rev = "9a1f8d7" }
rawtime = { git = "https://github.com/gz/rawtime.git", rev = "84466b2" }
lineup = { git = "https://github.com/gz/lineup.git", rev = "8d94274" }
log = "0.4"


[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[dependencies.num-traits]
version = "0.2.8"
default-features = false

