[package]
name = "ixgbe"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

[lib]
crate-type = ["staticlib"]
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
lto = true

[dependencies]
syscalls = { path = "../../../sys/interfaces/syscalls", version = "0.1.0" }
libsyscalls = { path = "../../../sys/lib/libsyscalls", version = "0.1.0" }
libtime = { path = "../../../sys/lib/libtime", version = "0.1.0" }
console = { path = "../../../sys/lib/console", version = "0.1.0" }
malloc = { path = "../../../sys/lib/malloc", version = "0.1.0" }
rref = { path = "../../lib/rref", version = "0.1.0" }
spin = { path = "../../../lib/spin-rs" }
bitflags = "1.0.4"
ixgbe_device = { path = "../../../sys/interfaces/device/ixgbe", version = "0.1.0" }
pci_driver = { path = "../../../sys/interfaces/dev/pci/pci_driver", version = "0.1.0" }
protocol = { path = "../../../sys/interfaces/protocol", version = "0.1.0" }
platform = { path = "../../../sys/interfaces/platform", version = "0.1.0" }
usr = { path = "../../../sys/interfaces/usr", version = "0.1.0" }
b2histogram = "1.0"
byteorder = { version = "1.3.4", default-features = false }
sashstore-redleaf = { path = "../../lib/sashstore" }
libbenchnet = { path = "../../lib/libbenchnet", version = "0.1.0" }

[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[dependencies.num-traits]
version = "0.2.8"
default-features = false


[dependencies.smoltcp]
path = "../../lib/smoltcp"
default-features = false
features = ["alloc", "proto-ipv4", "socket-tcp", "socket-icmp", "ethernet"]

[dependencies.arrayvec]
version = "0.5.1"
default-features = false

[dependencies.httparse]
path = "../../lib/httparse"
default-features = false

#[features]
#default = [
#    "nullnet",
#]

#nullnet = []
